name: Auto commit

on:
  schedule:
    - cron: "*/5 * * * *"   # tiap 5 menit (UTC)
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update LAST_UPDATED
        run: |
          date -u '+%Y-%m-%dT%H:%M:%SZ' > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "daniel222mu@gmail.com"
          git config --local user.name "Sipangkar"

          git add LAST_UPDATED

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          messages=(
            "chore(bot): ğŸ˜‚ auto commit"
            "chore(bot): ğŸ¤– auto commit"
            "chore(bot): ğŸ‘» auto commit"
            "chore(bot): ğŸŸ© auto commit"
            "chore(bot): ğŸ™ auto commit"
          )

          rand=$((RANDOM % ${#messages[@]}))
          git commit -m "${messages[$rand]}"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
